/**
 * JurisAccess AI - Citation & Statutory Grounding Validator
 * Detects hallucinated precedents and validates statutory citation formatting.
 */

export interface CitationAuditResult {
  isValid: boolean;
  flaggedCitations: string[];
  reason?: string;
}

// Hallucination indicators frequently generated by ungrounded LLMs
const HALLUCINATED_PATTERNS = [
  /\[citation\s+needed\]/i,
  /\[insert\s+(case|statute|citation)\]/i,
  /\b[A-Z][a-z]+\s+v\.\s+Fake[A-Za-z]+\b/i,
  /\bSection\s+99999\b/i,
  /\bXX\s+U\.S\.C\.\s+§\b/i,
];

// Legitimate statutory citation formats in civil legal aid
const STATUTORY_CITATION_PATTERNS = [
  /\b\d+\s+U\.S\.C\.\s+§\s*[\d\w.-]+/i,                      // Federal code (e.g. 15 U.S.C. § 1692)
  /\b(?:Cal\.|N\.Y\.|Tex\.|Fla\.|Ill\.)\s+[A-Za-z\s.]+§\s*[\d\w.-]+/i, // State codes
  /\bURLTA\s+§\s*[\d.]+/i,                                    // Uniform Residential Landlord and Tenant Act
  /\bCivil\s+Code\s+§\s*[\d.]+/i,
  /\bLabor\s+Code\s+§\s*[\d.]+/i,
];

export class CitationValidator {
  /**
   * Scans generated analysis for hallucinated citation placeholders or fake precedents
   */
  public static validate(text: string): CitationAuditResult {
    const flaggedCitations: string[] = [];

    for (const pattern of HALLUCINATED_PATTERNS) {
      const match = text.match(pattern);
      if (match) {
        flaggedCitations.push(match[0]);
      }
    }

    if (flaggedCitations.length > 0) {
      return {
        isValid: false,
        flaggedCitations,
        reason: `Detected ungrounded or placeholder citations: ${flaggedCitations.join(', ')}`,
      };
    }

    return { isValid: true, flaggedCitations: [] };
  }

  /**
   * Extracts recognized statutory citations from the text
   */
  public static extractRecognizedCitations(text: string): string[] {
    const recognized: string[] = [];
    for (const pattern of STATUTORY_CITATION_PATTERNS) {
      const matches = text.match(pattern);
      if (matches) {
        recognized.push(...matches);
      }
    }
    return Array.from(new Set(recognized));
  }
}
